apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - port: 1883
      targetPort: 1883
      name: mosquitto-mqtt
    - port: 9001
      targetPort: 9001
      name: mosquitto-otherport
  externalIPs:
    - 192.168.1.14
