apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mosquitto
  labels:
    app: mosquitto
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data
    log_dest file /mosquitto/log
