apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-claim
  namespace: mosquitto
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      directory: data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-log-claim
  namespace: mosquitto
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      directory: log
