apiVersion: v1
kind: Service
metadata:
  name: mosquitto-other
  namespace: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - port: 9001
      targetPort: 9001
      name: mosquitto-otherport
  externalIPs:
    - 192.168.1.14
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
  externalIPs:
    - 192.168.1.14
