apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-etc-localtime-claim
  namespace: openhab
spec:
  storageClassName: local
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      directory: localtime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-addons-claim
  namespace: openhab
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  selector:
    matchLabels:
      directory: addons
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-conf-claim
  namespace: openhab
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  selector:
    matchLabels:
      directory: conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-userdata-claim
  namespace: openhab
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: userdata
