apiVersion: v1
kind: PersistentVolume
metadata:
  name: openhab-addons-volume
  labels:
    directory: addons
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /data/openhab/addons
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openhab-conf-volume
  labels:
    directory: conf
spec:
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /data/openhab/conf
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openhab-userdata-volume
  labels:
    directory: userdata
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local
  local:
    path: /data/openhab/userdata
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi
