apiVersion: v1
kind: Service
metadata:
  name: openhab
  namespace: openhab
spec:
  selector:
    app: openhab
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: openhab-http
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: openhab-https
  externalIPs:
    - 192.168.1.14
