apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhab
  namespace: openhab
  labels:
    app: openhab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhab
  template:
    metadata:
      labels:
        app: openhab
        name: openhab
    spec:
      containers:
      - name: openhab
        image: openhab/openhab:4.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 800Mi
        env:
        - name: USER_ID
          valueFrom:
            configMapKeyRef:
              name: openhab-config
              key: USER_ID
        - name: GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: openhab-config
              key: GROUP_ID
        - name: CRYPTO_POLICY
          valueFrom:
            configMapKeyRef:
              name: openhab-config
              key: CRYPTO_POLICY
        - name: EXTRA_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: openhab-config
              key: EXTRA_JAVA_OPTS
        - name: OPENHAB_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: openhab-config
              key: OPENHAB_HTTP_PORT
        - name: OPENHAB_HTTPS_PORT
          valueFrom:
            configMapKeyRef:
              name: openhab-config
              key: OPENHAB_HTTPS_PORT
        volumeMounts:
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: openhab-addons
            mountPath: /openhab/addons
          - name: openhab-conf
            mountPath: /openhab/conf
          - name: openhab-userdata
            mountPath: /openhab/userdata
      volumes:
        - name: timezone
          configMap:
            name: openhab-config
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        - name: openhab-addons
          persistentVolumeClaim:
            claimName: openhab-addons-claim
        - name: openhab-conf
          persistentVolumeClaim:
            claimName: openhab-conf-claim
        - name: openhab-userdata
          persistentVolumeClaim:
            claimName: openhab-userdata-claim
---
apiVersion: v1
kind: Service
metadata:
  name: openhab
  namespace: openhab
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.10.3
spec:
  selector:
    app: openhab
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: openhab-http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: openhab-https
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openhab-config
  namespace: openhab
  labels:
    app: openhab
data:
  timezone: |
    "Europe/Stockholm"
  CRYPTO_POLICY: "unlimited"
  EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Stockholm"
  OPENHAB_HTTP_PORT: "80"
  OPENHAB_HTTPS_PORT: "443"
  USER_ID: "1005"
  GROUP_ID: "1005"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-addons-claim
  namespace: openhab
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeName: openhab-addons-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-conf-claim
  namespace: openhab
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeName: openhab-conf-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-userdata-claim
  namespace: openhab
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: openhab-userdata-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openhab-addons-volume
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.home
    path: "/volume1/ClusterShare/openhab/addons"
  mountOptions:
    - nfsvers=3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openhab-conf-volume
  labels:
    directory: conf
spec:
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.home
    path: "/volume1/ClusterShare/openhab/conf"
  mountOptions:
    - nfsvers=3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openhab-userdata-volume
  labels:
    directory: userdata
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.home
    path: "/volume1/ClusterShare/openhab/userdata"
  mountOptions:
    - nfsvers=3
