apiVersion: v1
kind: Service
metadata:
  name: tuya-svc
  namespace: tuya
spec:
  selector:
    app: tuya
  ports:
    - port: 6668
      targetPort: 6668
      name: tuya
  externalIPs:
    - 192.168.1.14
