apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: internal-pool
spec:
  addresses:
    - 192.168.1.100-192.168.1.110

---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  namespace: metallb-system
  name: my-peer
spec:
  myASN: 64512
  peerASN: 64512
  peerAddress: 192.168.1.1

---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  namespace: metallb-system
  name: advertisement
spec:
  ipAddressPools:
    - internal-pool

