apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-claim
  namespace: unifi
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      directory: config

