apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: unifi
spec:
  selector:
    app: unifi
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: unifi-device-comm
  - port: 9443
    targetPort: 8443
    protocol: TCP
    name: unifi-web-admin
  - port: 3478
    targetPort: 3478
    protocol: UDP
    name: unifi-stun
  - port: 10001
    targetPort: 10001
    protocol: UDP
    name: unifi-discovery
  externalIPs:
  - 192.168.1.14

