apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-config-volume
  labels:
    directory: config
spec:
  capacity:
    storage: 1024Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /data/unifi/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - raspberrypi

